### ISSUE TITLE
Dockerize한 frontend application 컨테이너가 앱을 빌드하지 못하는 현상

### ISSUE THREAD

**Issue by bnbong** [bnbong/Project-Pinned#7]
front/ 폴더에 다음과 같이 Dockerfile을 추가하여 컨테이너 빌드 스크립트를 짰다.
```
# Start from the official Node.js LTS base image
FROM node:16-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci
# RUN npm install

# Copy the rest of the code
COPY . .

# Build the app
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
```

해당 Dockerfile 스크립트를 통해 docker compose up 명령어를 입력하여 전체 프로젝트 빌드를 수행했더니 다음과 같은 오류가 발생했다.

![스크린샷 2023-06-27 오후 9 05 33](https://github.com/bnbong/Project-Pinned/assets/55042923/43bc7792-c173-4e28-bd3c-3f02987ec793)

위 사진과 같이 frontend 앱을 컨테이너가 빌드하는 과정에서 오류 로그로
```
project-pinned-frontend-1  | 
project-pinned-frontend-1  | > front@0.1.0 start
project-pinned-frontend-1  | > next start
project-pinned-frontend-1  | 
project-pinned-frontend-1  | sh: next: not found
project-pinned-frontend-1 exited with code 127
```
가 발생했다.

## 프로젝트 디렉토리 변경사항
루트 디렉토리 project-pinned에 있던 Dockerfile은 backend application을 빌드하기 위한 Dockerfile 이었다.

프론트앤드 앱과 백앤드 앱을 분리하여 빌드를 수행하도록 docker-compose.yml을 다음과 같이 수정함에 따라 프론트 프로젝트와 백엔드 프로젝트에 새로 Dockerfile을 각각 정의했다.

 - 변경한 docker-compose.yml 파일
```
version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: pinned_db
      POSTGRES_USER: pinned
      POSTGRES_PASSWORD: pinned
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./project_pinned
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project_pinned:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

volumes:
  postgres_data:
  redis_data:
```

**백엔드 앱의 Dockerfile이 Django 프로젝트 폴더 내부로 이동하게 되면서 .env 파일과 requirements.txt 파일 또한 같이 이동하게 되었다.** -> README.md 파일의 디렉토리 트리 부분 수정 예정.
